### ISSUE TITLE
Review / Suggestions / Feedback

### ISSUE THREAD

**Issue by southwood** [scsouthw/project-oxford-python#1]
@bogdanbe @crwilcox

I am kind of new to python and would greatly appreciate any feedback / suggestions or general commentary on this library. It is largely a port of @felixrieseberg's [library for node.js](https://github.com/felixrieseberg/project-oxford/) I'm using it for a couple projects and things seems to be working.

Thanks!

**Comment by felixrieseberg** [comment]
Fantastic stuff! I think that @irjudson might actually be perfectly suited for a quick look.

**Comment by irjudson** [comment]
Hey!

I'm looking it over and it looks pretty sweet at first glance.

Have you run pep8 and pyflakes on it to see if it conforms to python coding
conventions?

you can do that automatically in travis (see:
http://cramer.io/2012/05/03/using-travis-ci/)

Also, on the readme the dev enviroment was python 2.7, but none of the
other things are required - you might not want to include them.

and finally, if you include a requirements.txt (like a package.json) you
can do pip install -r requirements.txt and not have to enumerate them in
your readme (in case they change).

You want me to fork and PR these things or just provide feedback in email?

--Ivan

Ivan R. Judson
irjudson.org
(425) 679-1375

**Comment by southwood** [comment]
Thanks @irjudson! I haven't tried running pep8 or pyflakes but conforming to python coding conventions seems like a good idea :)

Fork and PR would be awesome if you have time. If not I'll try to do it sometime next week.
