### ISSUE TITLE
API version

### ISSUE THREAD

**Issue by pirakleous** [scsouthw/project-oxford-python#7]
Can you change the api version from v0 to v1?

**Comment by southwood** [comment]
I gave @zooba control of the PIP package (https://pypi.python.org/pypi/projectoxford/0.2.0) and he has been publishing from this repo: https://github.com/zooba/projectoxford (Note: this is probably the source of the error in #8). It looks like there is still not support for any of the image-based APIs. @irjudson do you know where this landed? Should I deprecate this repo or is it still the primary source for using the oxford image APIs from python?

**Comment by zooba** [comment]
I'm inclined to give it back, now that it's been renamed to Cortana Intelligence Suite, and you seem to have more willing contributors than I do. Interested?

**Comment by irjudson** [comment]
I can't tell who you're talking to Steve, but I'd be happy to take
ownership and drive the python client forward. I've got time and interest,
what's your plan scott?

-Ivan

Ivan R. Judson
irjudson.org
(425) 679-1375

**Comment by southwood** [comment]
I'm happy to hand off ownership. I'm no longer with Microsoft and unfortunately haven't been working with python as much lately.

Given the rename, I think the ideal situation would be to have one python package for each API suite provided by Cortana Intelligence (formerly project oxford). For example cortana-intel-vision, cortana-intel-speech, cortana-intel-language, cortana-intel-knowledge, and cortana-intel-search. Currently this repo contains a client for vision APIs and @zooba's repo contains a client for speech and a client for the vision/emotion API with a dependency on open CV.

@lightfrenzy, do you have any input on this? Is there any interest from your team around owning or maintaining the open-source python clients for Cortana Intelligence?
