### ISSUE TITLE
Error run pip command

### ISSUE THREAD

**Issue by pirakleous** [scsouthw/project-oxford-python#8]
Hello i am trying to install it with pip install projectoxford and i am getting this error:

Downloading/unpacking projectoxford
  Downloading projectoxford-0.3.1.zip
  Running setup.py (path:/tmp/pip-build-y3pBs5/projectoxford/setup.py) egg_info for package projectoxford
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-y3pBs5/projectoxford/setup.py", line 12, in <module>
        with open('README', 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-y3pBs5/projectoxford/setup.py", line 12, in <module>

```
with open('README', 'r', encoding='utf-8') as f:
```

TypeError: 'encoding' is an invalid keyword argument for this function

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-y3pBs5/projectoxford
Storing debug log for failure in /home/panagorn/.pip/pip.log

**Comment by gkrishna9790** [comment]
Even I ran into the same issue with projectoxford. Have no idea how to proceed. Please let me know if you have found a solution for the same. 

Thanks.

**Comment by zooba** [comment]
The latest versions of `projectoxford` are for Python 3 only. It's a different library.

If you want the one that was maintained here, install `projectoxford<0.3`
